# Generated by Django 4.1 on 2022-08-07 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssh', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hosts',
            new_name='Host',
        ),
    ]
